project_id = "your-project-id-here"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[ingest]
enabled = false

[storage]
enabled = true
file_size_limit = "5MiB"

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["exp://127.0.0.1:8081"]

[functions]
enabled = true
verify_jwt = true
